from __future__ import annotations

from datetime import date, time
from typing import Any, Optional

ZODIAC = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
]

HOUSE_THEMES = [
    "Self & identity",
    "Resources & values",
    "Communication",
    "Home & roots",
    "Creativity & joy",
    "Work & health",
    "Partnerships",
    "Transformation",
    "Beliefs & travel",
    "Career & status",
    "Community & hopes",
    "Rest & release",
]

PLANETS = [
    "Sun",
    "Moon",
    "Mars",
    "Mercury",
    "Jupiter",
    "Venus",
    "Saturn",
    "Rahu",
    "Ketu",
]

THEME_POOL = [
    "Steady growth through patient effort",
    "Partnerships open unexpected doors",
    "Communication sharpens career timing",
    "Home foundations support bold moves",
    "Creative focus renews confidence",
    "Discipline converts ambition into results",
]


def hash_seed(text: str) -> int:
    h = 2166136261
    for ch in text:
        h ^= ord(ch)
        h = (h * 16777619) & 0xFFFFFFFF
    return h


def longitude_to_sign_degree(longitude: float) -> tuple[str, float]:
    lon = longitude % 360.0
    idx = int(lon // 30) % 12
    return ZODIAC[idx], lon % 30.0


def build_stub_chart(
    *,
    birth_profile_id: Optional[str],
    full_name: str,
    birth_date: date,
    unknown_birth_time: bool,
    latitude: Optional[float],
    longitude: Optional[float],
    language: str,
) -> dict[str, Any]:
    lat = latitude if latitude is not None else 6.9271
    lon = longitude if longitude is not None else 79.8612
    seed = hash_seed(f"{birth_date.isoformat()}|{full_name}|{lat}|{lon}")
    lagna_index = seed % 12
    lagna_degree = ((seed >> 8) % 3000) / 100.0

    planets = []
    for i, name in enumerate(PLANETS):
        p_seed = (seed + (i + 1) * 9973) & 0xFFFFFFFF
        planets.append(
            {
                "name": name,
                "sign": ZODIAC[p_seed % 12],
                "degree": ((p_seed >> 4) % 3000) / 100.0,
                "house": (p_seed % 12) + 1,
                "longitude": float((p_seed % 36000) / 100.0),
                "retrograde": False,
            }
        )

    houses = [
        {
            "number": i + 1,
            "sign": ZODIAC[(lagna_index + i) % 12],
            "theme": theme,
            "cuspLongitude": float(((lagna_index + i) * 30) % 360),
        }
        for i, theme in enumerate(HOUSE_THEMES)
    ]

    themes = [THEME_POOL[(seed + i * 5) % len(THEME_POOL)] for i in range(3)]
    notes = [
        "Deterministic chart stub — Swiss Ephemeris unavailable in this runtime.",
        "Generated by astrology-engine stub fallback.",
    ]
    if unknown_birth_time:
        notes.append("Birth time unknown or approximate; chart accuracy reduced.")

    return {
        "engineVersion": "stub-0.3.0",
        "placeholder": True,
        "system": "sidereal-stub",
        "ayanamsa": "Lahiri-approx",
        "birthProfileId": birth_profile_id,
        "language": language,
        "lagna": {
            "sign": ZODIAC[lagna_index],
            "degree": lagna_degree,
            "longitude": float(lagna_index * 30 + lagna_degree),
            "houseSystem": "WholeSign",
        },
        "planets": planets,
        "houses": houses,
        "themes": themes,
        "notes": notes,
    }
