import {
  ChartResult,
  HOUSE_THEMES,
  PLANET_NAMES,
  ZODIAC_SIGNS,
} from './types';

/** Stable 32-bit hash for deterministic chart stubs */
export function hashSeed(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function buildLocalChart(input: {
  birthProfileId?: string | null;
  fullName: string;
  birthDate: string;
  unknownBirthTime: boolean;
  latitude?: number | null;
  longitude?: number | null;
  language: string;
  source?: 'worker-local' | 'engine-mirror';
}): ChartResult {
  const seed = hashSeed(
    [
      input.birthDate,
      input.fullName,
      String(input.latitude ?? 6.9271),
      String(input.longitude ?? 79.8612),
    ].join('|'),
  );

  const lagnaIndex = seed % 12;
  const lagnaDegree = ((seed >>> 8) % 3000) / 100;

  const planets = PLANET_NAMES.map((name, i) => {
    const pSeed = (seed + (i + 1) * 9973) >>> 0;
    const longitude = ((pSeed % 36000) / 100) % 360;
    return {
      name,
      sign: ZODIAC_SIGNS[pSeed % 12],
      degree: ((pSeed >>> 4) % 3000) / 100,
      house: (pSeed % 12) + 1,
      longitude,
      retrograde: name === 'Ketu' || name === 'Saturn' ? (pSeed & 1) === 1 : false,
    };
  });

  const houses = HOUSE_THEMES.map((theme, i) => ({
    number: i + 1,
    sign: ZODIAC_SIGNS[(lagnaIndex + i) % 12],
    theme,
  }));

  const themePool = [
    'Steady growth through patient effort',
    'Partnerships open unexpected doors',
    'Communication sharpens career timing',
    'Home foundations support bold moves',
    'Creative focus renews confidence',
    'Discipline converts ambition into results',
  ];
  const themes = [0, 1, 2].map((i) => themePool[(seed + i * 5) % themePool.length]);

  const notes = [
    'Deterministic chart stub — Swiss Ephemeris not yet integrated.',
    input.source === 'worker-local'
      ? 'Generated by worker local fallback (engine unavailable).'
      : 'Generated by astrology-engine stub.',
  ];
  if (input.unknownBirthTime) {
    notes.push('Birth time unknown or approximate; chart accuracy reduced.');
  }

  return {
    engineVersion:
      input.source === 'worker-local' ? 'worker-local-stub-0.2.0' : 'stub-0.2.0',
    placeholder: true,
    birthProfileId: input.birthProfileId ?? null,
    language: input.language,
    lagna: {
      sign: ZODIAC_SIGNS[lagnaIndex],
      degree: lagnaDegree,
      houseSystem: 'Placidus',
    },
    planets,
    houses,
    themes,
    notes,
  };
}
